# Generated by Django 4.2.29 on 2026-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("preparation", models.CharField(max_length=100)),
                ("calories", models.IntegerField()),
                ("total_fat_g", models.FloatField(blank=True, null=True)),
                ("sugar_g", models.IntegerField(blank=True, null=True)),
                ("caffeine_mg", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
